# Exported from Render on 2025-08-02T15:09:45Z
databases:
- name: n8n-postgres
  databaseName: n8n_db
  user: n8n_user
  plan: free
  region: oregon
  ipAllowList: []

services:
- type: web
  name: n8n-gitops-engine
  runtime: docker
  repo: https://github.com/AI-Tool-Pool/my-n8n-render
  plan: free
  envVars:
  - key: N8N_HOST
    sync: false
  - key: N8N_PORT
    sync: false
  - key: N8N_METRICS_ENABLED
    sync: false
  - key: N8N_BASIC_AUTH_PASSWORD
    sync: false
  - key: N8N_BASIC_AUTH_USER
    sync: false
  - key: N8N_BASIC_AUTH_ACTIVE
    sync: false
  - key: N8N_ENCRYPTION_KEY
    sync: false
  - key: DB_TYPE
    value: postgresdb
  - key: DB_POSTGRESDB_HOST
    fromDatabase:
      name: n8n-postgres
      property: host
  - key: DB_POSTGRESDB_PORT
    fromDatabase:
      name: n8n-postgres
      property: port
  - key: DB_POSTGRESDB_DATABASE
    fromDatabase:
      name: n8n-postgres
      property: database
  - key: DB_POSTGRESDB_USER
    fromDatabase:
      name: n8n-postgres
      property: user
  - key: DB_POSTGRESDB_PASSWORD
    fromDatabase:
      name: n8n-postgres
      property: password
  - key: DB_POSTGRESDB_SSL
    value: "false"
  - key: DB_POSTGRESDB_SCHEMA
    value: public
  - key: EXECUTIONS_DATA_SAVE_ON_ERROR
    sync: false
  - key: EXECUTIONS_DATA_SAVE_ON_SUCCESS
    sync: false
  - key: EXECUTIONS_DATA_MAX_AGE
    sync: false
  - key: EXECUTIONS_DATA_PRUNE
    sync: false
  - key: N8N_LOG_LEVEL
    sync: false
  - key: TZ
    sync: false
  - key: GENERIC_TIMEZONE
    sync: false
  - key: N8N_RUNNERS_ENABLED
    sync: false
  - key: N8N_BASIC_AUTH_ACTIVE
    sync: false
  - key: N8N_ENCRYPTION_KEY
    sync: false
  - key: WEBHOOK_URL
    sync: false
  - key: PORT
    sync: false
  region: oregon
  dockerCommand: docker run -p 5678:5678
  dockerContext: .
  dockerfilePath: ./Dockerfile
  autoDeployTrigger: commit
version: "1"
