services:
  - type: web
    name: n8n-gitops-engine
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    region: oregon
    envVars:
      # Database (using single URL for clarity)
      - key: DATABASE_URL
        fromSecret: DATABASE_URL
      
      # Security
      - key: N8N_BASIC_AUTH_USER
        fromSecret: N8N_BASIC_AUTH_USER
      - key: N8N_BASIC_AUTH_PASSWORD
        fromSecret: N8N_BASIC_AUTH_PASSWORD
      - key: N8N_ENCRYPTION_KEY
        fromSecret: N8N_ENCRYPTION_KEY
      
      # Application
      - key: EXECUTIONS_DATA_MAX_AGE
        value: "336"
      - key: EXECUTIONS_DATA_PRUNE
        value: "true"
      - key: GENERIC_TIMEZONE
        value: "America/New_York"
      - key: N8N_HOST
        value: "0.0.0.0"
      - key: N8N_PORT
        value: "5678"
      - key: WEBHOOK_URL
        fromService:
          type: web
          name: n8n-gitops-engine
          property: defaultURL
      - key: N8N_METRICS_ENABLED
        value: "false"
    
    healthCheckPath: /healthz
    restartPolicy: unless-stopped