# Exported from Render on 2025-08-02T15:09:45Z
databases:
- name: n8n-postgres
  databaseName: n8n_db
  user: n8n_user
  plan: free
  region: oregon
  ipAllowList: []

services:
- type: web
  name: n8n-gitops-engine
  runtime: docker
  repo: https://github.com/AI-Tool-Pool/my-n8n-render
  plan: free
  envVars:
  - key: N8N_HOST
    value: "0.0.0.0"
  - key: N8N_PORT
    value: "5678"
  - key: PORT
    value: "5678"
  - key: N8N_METRICS_ENABLED
    value: "false"
  - key: N8N_BASIC_AUTH_PASSWORD
    generateValue: true
  - key: N8N_BASIC_AUTH_USER
    value: "admin"
  - key: N8N_BASIC_AUTH_ACTIVE
    value: "true"
  - key: N8N_ENCRYPTION_KEY
    generateValue: true
  - key: WEBHOOK_URL
    value: "https://n8n-gitops-engine.onrender.com"
  - key: DB_TYPE
    value: postgresdb
  - key: DB_POSTGRESDB_HOST
    fromDatabase:
      name: n8n-postgres
      property: host
  - key: DB_POSTGRESDB_PORT
    fromDatabase:
      name: n8n-postgres
      property: port
  - key: DB_POSTGRESDB_DATABASE
    fromDatabase:
      name: n8n-postgres
      property: database
  - key: DB_POSTGRESDB_USER
    fromDatabase:
      name: n8n-postgres
      property: user
  - key: DB_POSTGRESDB_PASSWORD
    fromDatabase:
      name: n8n-postgres
      property: password
  - key: DB_POSTGRESDB_SSL
    value: "false"
  - key: DB_POSTGRESDB_SCHEMA
    value: public
  - key: EXECUTIONS_DATA_SAVE_ON_ERROR
    value: "all"
  - key: EXECUTIONS_DATA_SAVE_ON_SUCCESS
    value: "none"
  - key: EXECUTIONS_DATA_MAX_AGE
    value: "72"
  - key: EXECUTIONS_DATA_PRUNE
    value: "true"
  - key: EXECUTIONS_TIMEOUT
    value: "600"
  - key: EXECUTIONS_TIMEOUT_MAX
    value: "1200"
  - key: N8N_LOG_LEVEL
    value: "warn"
  - key: TZ
    value: "UTC"
  - key: GENERIC_TIMEZONE
    value: "UTC"
  - key: N8N_RUNNERS_ENABLED
    value: "false"
  - key: N8N_TEMPLATES_ENABLED
    value: "true"
  - key: N8N_ONBOARDING_FLOW_DISABLED
    value: "true"
  - key: N8N_HIRING_BANNER_ENABLED
    value: "false"
  - key: N8N_PERSONALIZATION_ENABLED
    value: "false"
  - key: N8N_VERSION_NOTIFICATIONS_ENABLED
    value: "false"
  - key: N8N_DIAGNOSTICS_ENABLED
    value: "false"
  - key: N8N_BINARY_DATA_MODE
    value: "filesystem"
  - key: N8N_BINARY_DATA_TTL
    value: "30"
  - key: N8N_PERSISTED_BINARY_DATA_TTL
    value: "720"
  - key: N8N_CACHE_BACKEND
    value: "memory"
  - key: NODE_OPTIONS
    value: "--max-old-space-size=400 --max-http-header-size=81920"
  region: oregon
  dockerCommand: ./entrypoint.sh
  dockerContext: .
  dockerfilePath: ./Dockerfile
  healthCheckPath: /
  autoDeployTrigger: commit
version: "1"
